trigger:
- main

pool:
  vmImage: 'ubuntu-20.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Nevotech Acr'
    repository: 'countdown-core'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 1.0.$(Build.BuildNumber)