trigger:
- main

pool:
  vmImage: 'ubuntu-20.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: DotNet Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    includeNuGetOrg: true

- task: DotNetCoreCLI@2
  displayName: DotNet Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory) --no-restore'

- task: Docker@2
  inputs:
    buildContext: $(Build.ArtifactStagingDirectory)
    containerRegistry: 'Nevotech Acr'
    repository: 'countdown-core'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 1.0.$(Build.BuildNumber)